# -*- mode: ruby-ts;-*-
# An example of OS-specific packages:
# install only on specified OS
#brew "gnupg" if OS.mac?
#brew "glibc" if OS.linux?
tap "homebrew/bundle"

brew "mas" if OS.mac?
brew "terminal-notifier" if OS.mac?

cask "1password"
cask "alfred"
cask "arq"
cask "balenaetcher"
cask "calibre"
cask "daisydisk"
cask "dash"
cask "discord"
cask "istat-menus"
cask "launchcontrol"
cask "monitorcontrol"
cask "obsidian"
cask "plexamp"
cask "rectangle"
cask "slack"
cask "spotify"
cask "syncthing"
cask "transmit"

mas "Deliveries", id: 290986013
mas "Ivory", id: 6444602274
mas "Tailscale", id: 1475387142
mas "Things", id: 904280696
