#!/usr/bin/env bash
for app in ~/.nix-profile/Applications/*
do
    if ! [[ -e ~/nix-apps/${app#~/.nix-profile/Applications/} ]]
    then
        echo installing new app "${app#~/.nix-profile/Applications/}"
        cp -Rl -- "$app" ~/nix-apps
    elif ! diff -qr "$app" ~/nix-apps/"${app#~/.nix-profile/Applications/}" 1> /dev/null
    then
        echo updating "${app#~/.nix-profile/Applications/}"
	cp -Rl -- "$app" ~/nix-apps
    fi
done

for app in ~/nix-apps/*
do
    if ! [[ -e ~/.nix-profile/Applications/${app#~/nix-apps/} ]]
    then
        echo "$app is getting removed"
        rm -- "$app"
    fi
done
